default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: city_news_development

test:
  <<: *default
  database: city_news_test

production:
  <<: *default
  database: city_news_production
  username: citynews
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>
